Repository goorm-dofarming/Backend, pull requests merged in 2024-07, with the labels that each got.

#1 feature/RAND-80
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/entity/Chatroom.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/join/entity/Join.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/like/entity/Like.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/location/entity/Location.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/log/entity/Log.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/recommend/entity/Recommend.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/region/entity/Region.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/tag/entity/Tag.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/user/entity/Role.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/user/entity/User.java
  dofarming/src/main/java/goorm/dofarming/domain/mongo/message/entity/Message.java
  dofarming/src/main/java/goorm/dofarming/global/common/entity/BaseEntity.java
  dofarming/src/main/java/goorm/dofarming/global/common/entity/Status.java
Labels: feat

#2 feature/RAND-81
  dofarming/build.gradle
  dofarming/src/main/java/goorm/dofarming/DofarmingApplication.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/join/entity/Join.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/like/entity/Like.java
  dofarming/src/main/java/goorm/dofarming/global/config/JpaConfig.java
  dofarming/src/main/java/goorm/dofarming/global/config/MongoConfig.java
  dofarming/src/main/resources/application.properties
  dofarming/src/main/resources/application.yml
  dofarming/src/test/resources/application.yml
Labels: test, feat

#3 feature/RAND-82
  dofarming/src/main/java/goorm/dofarming/global/common/exception/CustomException.java
  dofarming/src/main/java/goorm/dofarming/global/common/exception/ErrorCode.java
  dofarming/src/main/java/goorm/dofarming/global/common/exception/ErrorResponse.java
  dofarming/src/main/java/goorm/dofarming/global/common/exception/GlobalExceptionHandler.java
Labels: feat

#4 feature/RAND-12
  dofarming/build.gradle
  dofarming/src/main/java/goorm/dofarming/domain/jpa/user/controller/UserController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/user/dto/request/UserModifyRequest.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/user/dto/request/UserSignUpRequest.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/user/dto/response/UserResponse.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/user/entity/User.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/user/repository/UserRepository.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/user/service/UserService.java
  dofarming/src/main/java/goorm/dofarming/global/common/util/RandomNicknameGenerator.java
  dofarming/src/main/resources/application.yml
  dofarming/src/test/java/goorm/dofarming/domain/jpa/user/service/UserServiceTest.java
Labels: test, feat

#5 feature/RAND-54
  dofarming/build.gradle
  dofarming/src/main/java/goorm/dofarming/domain/jpa/auth/dto/response/AuthDto.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/user/controller/UserController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/user/dto/request/UserSignUpRequest.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/user/service/UserService.java
  dofarming/src/main/java/goorm/dofarming/global/auth/DofarmingUserDetails.java
  dofarming/src/main/java/goorm/dofarming/global/auth/DofarmingUserDetailsService.java
  dofarming/src/main/java/goorm/dofarming/global/common/error/ErrorCode.java
  dofarming/src/main/java/goorm/dofarming/global/common/error/ErrorResponse.java
  dofarming/src/main/java/goorm/dofarming/global/common/error/GlobalExceptionHandler.java
  dofarming/src/main/java/goorm/dofarming/global/common/error/exception/CustomException.java
  dofarming/src/main/java/goorm/dofarming/global/common/error/exception/CustomExpiredJwtException.java
  dofarming/src/main/java/goorm/dofarming/global/common/error/exception/CustomInvalidJwtException.java
  dofarming/src/main/java/goorm/dofarming/global/common/error/exception/CustomMalformedJwtException.java
  dofarming/src/main/java/goorm/dofarming/global/common/error/exception/CustomUnsupportedJwtException.java
  dofarming/src/main/java/goorm/dofarming/global/common/error/exception/DofarmingAccessDeniedHandler.java
  dofarming/src/main/java/goorm/dofarming/global/common/error/exception/DofarmingAuthenticationEntrypoint.java
  dofarming/src/main/java/goorm/dofarming/global/common/exception/CustomException.java
  dofarming/src/main/java/goorm/dofarming/global/common/exception/ErrorCode.java
  dofarming/src/main/java/goorm/dofarming/global/common/exception/ErrorResponse.java
  dofarming/src/main/java/goorm/dofarming/global/common/exception/GlobalExceptionHandler.java
  dofarming/src/main/java/goorm/dofarming/global/config/SecurityConfig.java
  dofarming/src/main/java/goorm/dofarming/global/filter/JwtAuthFilter.java
  dofarming/src/main/java/goorm/dofarming/global/util/JwtUtil.java
  dofarming/src/main/java/goorm/dofarming/global/util/RandomNicknameGenerator.java
  dofarming/src/main/resources/application.yml
  dofarming/src/test/java/goorm/dofarming/domain/jpa/user/service/UserServiceTest.java
Labels: feat

#15 feature/RAND-55
  dofarming/build.gradle
  dofarming/src/main/java/goorm/dofarming/DofarmingApplication.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/auth/controller/AuthController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/auth/dto/request/SignInRequest.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/auth/service/AuthService.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/email/controller/EmailController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/email/dto/request/EmailCheckRequest.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/email/dto/request/EmailRequest.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/email/service/EmailService.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/user/controller/UserController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/user/dto/request/UserModifyRequest.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/user/entity/User.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/user/repository/UserRepository.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/user/service/UserService.java
  dofarming/src/main/java/goorm/dofarming/global/auth/DofarmingUserDetails.java
  dofarming/src/main/java/goorm/dofarming/global/common/error/ErrorResponse.java
  dofarming/src/main/java/goorm/dofarming/global/common/error/GlobalExceptionHandler.java
  dofarming/src/main/java/goorm/dofarming/global/common/error/exception/DofarmingAccessDeniedHandler.java
  dofarming/src/main/java/goorm/dofarming/global/common/error/exception/DofarmingAuthenticationEntrypoint.java
  dofarming/src/main/java/goorm/dofarming/global/config/EmailConfig.java
  dofarming/src/main/java/goorm/dofarming/global/config/PasswordEncoderConfig.java
  dofarming/src/main/java/goorm/dofarming/global/config/SecurityConfig.java
  dofarming/src/main/java/goorm/dofarming/global/config/WebConfig.java
  dofarming/src/main/java/goorm/dofarming/global/filter/JwtAuthFilter.java
  dofarming/src/main/java/goorm/dofarming/global/util/ImageUtil.java
  dofarming/src/main/java/goorm/dofarming/global/util/OctetStreamReadMsgConverter.java
  dofarming/src/main/java/goorm/dofarming/global/util/RandomCodeGenerator.java
  dofarming/src/main/resources/application.yml
  dofarming/src/test/java/goorm/dofarming/domain/jpa/user/service/UserServiceTest.java
  dofarming/src/test/resources/application.yml
Labels: feat, remove

#44 feature/RAND-12 : DTO 별 swagger 적용
  dofarming/src/main/java/goorm/dofarming/domain/jpa/auth/dto/request/SignInRequest.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/email/dto/request/EmailCheckRequest.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/email/dto/request/EmailRequest.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/user/dto/request/UserModifyRequest.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/user/dto/request/UserSignUpRequest.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/user/dto/response/UserResponse.java
  dofarming/src/main/java/goorm/dofarming/global/common/error/ErrorResponse.java
Labels: feat

#46 feature/RAND-13
  dofarming/src/main/java/goorm/dofarming/domain/jpa/auth/controller/AuthController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/auth/dto/request/OauthRequest.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/auth/dto/response/AuthDto.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/auth/dto/response/MyInfoResponse.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/auth/service/AuthService.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/user/entity/Role.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/user/entity/User.java
  dofarming/src/main/java/goorm/dofarming/global/auth/DofarmingUserDetailsService.java
  dofarming/src/main/java/goorm/dofarming/global/auth/GoogleOAuth2UserInfo.java
  dofarming/src/main/java/goorm/dofarming/global/auth/KakaoOAuth2UserInfo.java
  dofarming/src/main/java/goorm/dofarming/global/auth/NaverOAuth2UserInfo.java
  dofarming/src/main/java/goorm/dofarming/global/auth/OAuth2UserInfo.java
  dofarming/src/main/resources/application.properties
Labels: feat

#47 feature/RAND-20
  dofarming/src/main/java/goorm/dofarming/domain/jpa/auth/controller/AuthController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/controller/ChatroomController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/dto/request/ChatroomCreateRequest.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/entity/Chatroom.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/entity/Region.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/repository/ChatroomRepository.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/service/ChatroomService.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/region/entity/Region.java
Labels: fix, refactor, feat

#48 feature/RAND-19
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/controller/ChatroomController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/service/ChatroomService.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/join/entity/Join.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/join/repository/JoinRepository.java
Labels: feat

#49 feature/RAND-79
  dofarming/build.gradle
  dofarming/src/main/java/goorm/dofarming/domain/jpa/auth/service/AuthService.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/dto/request/ChatroomCreateRequest.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/dto/request/ChatroomSearchRequest.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/dto/response/ChatroomResponse.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/entity/Chatroom.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/repository/ChatroomRepository.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/repository/ChatroomRepositoryCustom.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/repository/ChatroomRepositoryImpl.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/service/ChatroomService.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/tag/dto/request/TagRequest.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/tag/entity/Tag.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/tag/repository/TagRepository.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/tag/service/TagService.java
  dofarming/src/main/java/goorm/dofarming/domain/mongo/message/entity/Message.java
Labels: feat

#50 feature/RAND-79
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/controller/ChatroomController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/service/ChatroomService.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/join/repository/JoinRepository.java
Labels: feat

#51 feature/RAND-78
  chat/.gitignore
  chat/build.gradle
  chat/gradle/wrapper/gradle-wrapper.jar
  chat/gradle/wrapper/gradle-wrapper.properties
  chat/gradlew
  chat/gradlew.bat
  chat/settings.gradle
  chat/src/main/java/goorm/chat/ChatApplication.java
  chat/src/main/resources/application.properties
  chat/src/test/java/goorm/chat/ChatApplicationTests.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/controller/ChatroomController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/repository/ChatroomRepositoryImpl.java
Labels: fix, feat

#53 feature/RAND-78
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/controller/ChatroomController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/service/ChatroomService.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/email/service/EmailService.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/user/service/UserService.java
  dofarming/src/main/java/goorm/dofarming/global/util/RandomGenerator.java
  dofarming/src/main/resources/application.properties
Labels: fix

#54 feature/RAND-78
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/dto/request/ChatroomSearchRequest.java
  dofarming/src/main/java/goorm/dofarming/global/util/RandomGenerator.java
Labels: fix

#57 feature/RAND-78
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/dto/request/ChatroomSearchRequest.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/dto/response/ChatroomResponse.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/entity/Chatroom.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/repository/ChatroomRepositoryImpl.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/service/ChatroomService.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/join/entity/Join.java
Labels: fix, refactor, feat

#59 feature/RAND-78
  dofarming/src/main/java/goorm/dofarming/domain/mongo/message/service/MessageService.java
Labels: fix

#60 realse : fix: querydsl 환경설정 수정
  chat/src/main/java/goorm/chat/domain/Message.java
  chat/src/main/java/goorm/chat/dto/MessageResponse.java
  dofarming/src/main/java/goorm/dofarming/domain/mongo/message/dto/request/MessageSearchRequest.java
  dofarming/src/main/java/goorm/dofarming/domain/mongo/message/dto/response/MessageResponse.java
  dofarming/src/main/java/goorm/dofarming/domain/mongo/message/entity/Message.java
  dofarming/src/main/java/goorm/dofarming/domain/mongo/message/repository/MessageRepositoryImpl.java
Labels: fix

#61 feature/RAND-78
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/dto/request/ChatroomCreateRequest.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/dto/response/ChatroomResponse.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/service/ChatroomService.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/tag/dto/request/TagRequest.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/tag/dto/response/TagResponse.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/tag/service/TagService.java
  dofarming/src/main/java/goorm/dofarming/global/auth/OAuth2UserInfo.java
Labels: fix, feat

#63 feature/RAND-13
  dofarming/src/main/java/goorm/dofarming/domain/jpa/auth/service/AuthService.java
Labels: fix

#64 feature/RAND-114
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/controller/ChatroomController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/dto/request/ChatroomSearchRequest.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/dto/response/ChatroomResponse.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/entity/Region.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/repository/ChatroomRepositoryCustom.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/repository/ChatroomRepositoryImpl.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/service/ChatroomService.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/user/controller/UserController.java
  dofarming/src/main/java/goorm/dofarming/domain/mongo/message/controller/MessageController.java
  dofarming/src/main/java/goorm/dofarming/domain/mongo/message/dto/request/MessageSearchRequest.java
  dofarming/src/main/java/goorm/dofarming/domain/mongo/message/repository/MessageRepositoryCustom.java
  dofarming/src/main/java/goorm/dofarming/domain/mongo/message/repository/MessageRepositoryImpl.java
  dofarming/src/main/java/goorm/dofarming/domain/mongo/message/service/MessageService.java
Labels: fix

#65 Release to main
  dofarming/src/main/java/goorm/dofarming/domain/jpa/auth/service/AuthService.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/controller/ChatroomController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/dto/request/ChatroomSearchRequest.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/dto/response/ChatroomResponse.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/entity/Region.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/repository/ChatroomRepositoryCustom.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/repository/ChatroomRepositoryImpl.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/service/ChatroomService.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/user/controller/UserController.java
  dofarming/src/main/java/goorm/dofarming/domain/mongo/message/controller/MessageController.java
  dofarming/src/main/java/goorm/dofarming/domain/mongo/message/dto/request/MessageSearchRequest.java
  dofarming/src/main/java/goorm/dofarming/domain/mongo/message/repository/MessageRepositoryCustom.java
  dofarming/src/main/java/goorm/dofarming/domain/mongo/message/repository/MessageRepositoryImpl.java
  dofarming/src/main/java/goorm/dofarming/domain/mongo/message/service/MessageService.java
Labels: chore

#66 fix: 쿼리 파라미터 null 값 허용
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/controller/ChatroomController.java
  dofarming/src/main/java/goorm/dofarming/domain/mongo/message/controller/MessageController.java
Labels: fix

#67 Release to main
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/repository/ChatroomRepositoryImpl.java
Labels: fix

#68 Release to main
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/repository/ChatroomRepositoryImpl.java
  dofarming/src/main/resources/application.properties
Labels: fix, chore

#71 feature/RAND-105
  chat/build.gradle
  chat/src/main/java/goorm/chat/config/KafkaConstants.java
  chat/src/main/java/goorm/chat/config/KafkaConsumerConfig.java
  chat/src/main/java/goorm/chat/config/KafkaProducerConfig.java
  chat/src/main/java/goorm/chat/config/WebSocketConfig.java
  chat/src/main/java/goorm/chat/controller/MessageController.java
  chat/src/main/java/goorm/chat/domain/Message.java
  chat/src/main/java/goorm/chat/domain/MessageType.java
  chat/src/main/java/goorm/chat/dto/MessageDto.java
  chat/src/main/java/goorm/chat/dto/MessageRequest.java
  chat/src/main/java/goorm/chat/dto/MessageResponse.java
  chat/src/main/java/goorm/chat/repository/MessageRepository.java
  chat/src/main/java/goorm/chat/service/MessageService.java
  chat/src/main/resources/application.properties
  chat/src/main/resources/templates/index.html
  dofarming/build.gradle
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/dto/response/ChatroomResponse.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/entity/Region.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/user/service/UserService.java
  dofarming/src/main/java/goorm/dofarming/domain/mongo/message/controller/MessageController.java
  dofarming/src/main/java/goorm/dofarming/domain/mongo/message/dto/MessageDto.java
  dofarming/src/main/java/goorm/dofarming/domain/mongo/message/entity/Message.java
  dofarming/src/main/java/goorm/dofarming/domain/mongo/message/service/KafkaMessageService.java
  dofarming/src/main/java/goorm/dofarming/global/config/kafka/KafkaConstants.java
  dofarming/src/main/java/goorm/dofarming/global/config/kafka/KafkaConsumerConfig.java
  dofarming/src/main/java/goorm/dofarming/global/config/kafka/KafkaProducerConfig.java
  dofarming/src/main/java/goorm/dofarming/global/util/ImageUtil.java
  dofarming/src/main/resources/application.properties
Labels: fix, feat

#73 Release to main
  chat/build.gradle
  chat/src/main/java/goorm/chat/config/KafkaConstants.java
  chat/src/main/java/goorm/chat/config/KafkaConsumerConfig.java
  chat/src/main/java/goorm/chat/config/KafkaProducerConfig.java
  chat/src/main/java/goorm/chat/config/WebSocketConfig.java
  chat/src/main/java/goorm/chat/controller/MessageController.java
  chat/src/main/java/goorm/chat/domain/Message.java
  chat/src/main/java/goorm/chat/domain/MessageType.java
  chat/src/main/java/goorm/chat/dto/MessageDto.java
  chat/src/main/java/goorm/chat/dto/MessageRequest.java
  chat/src/main/java/goorm/chat/dto/MessageResponse.java
  chat/src/main/java/goorm/chat/repository/MessageRepository.java
  chat/src/main/java/goorm/chat/service/MessageService.java
  chat/src/main/resources/application.properties
  chat/src/main/resources/templates/index.html
  dofarming/build.gradle
  dofarming/src/main/java/goorm/dofarming/DofarmingApplication.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/dto/response/ChatroomResponse.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/entity/Region.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/user/service/UserService.java
  dofarming/src/main/java/goorm/dofarming/domain/mongo/message/controller/MessageController.java
  dofarming/src/main/java/goorm/dofarming/domain/mongo/message/dto/MessageDto.java
  dofarming/src/main/java/goorm/dofarming/domain/mongo/message/entity/Message.java
  dofarming/src/main/java/goorm/dofarming/domain/mongo/message/service/KafkaMessageService.java
  dofarming/src/main/java/goorm/dofarming/global/config/kafka/KafkaConstants.java
  dofarming/src/main/java/goorm/dofarming/global/config/kafka/KafkaConsumerConfig.java
  dofarming/src/main/java/goorm/dofarming/global/config/kafka/KafkaProducerConfig.java
  dofarming/src/main/java/goorm/dofarming/global/util/ImageUtil.java
  dofarming/src/main/java/goorm/dofarming/infra/tourapi/config/WebClientConfig.java
  dofarming/src/main/java/goorm/dofarming/infra/tourapi/controller/ApiController.java
  dofarming/src/main/java/goorm/dofarming/infra/tourapi/dto/Item.java
  dofarming/src/main/java/goorm/dofarming/infra/tourapi/service/ApiService.java
  dofarming/src/main/java/goorm/dofarming/infra/tourapi/service/ContentBasedApiService.java
  dofarming/src/main/java/goorm/dofarming/infra/tourapi/service/LocationBasedApiService.java
  dofarming/src/main/resources/application.properties
Labels: fix, chore

#74 fix: 직렬화 패키지 문제
  dofarming/src/main/java/goorm/dofarming/global/config/kafka/KafkaConsumerConfig.java
Labels: fix, chore

#75 fix: rest api 서버 역직렬화 수정
  dofarming/src/main/java/goorm/dofarming/global/config/kafka/KafkaConsumerConfig.java
Labels: fix

#76 fix:역직렬화 수정
  chat/src/main/java/goorm/chat/config/KafkaConsumerConfig.java
  chat/src/main/java/goorm/chat/config/KafkaProducerConfig.java
  chat/src/main/java/goorm/chat/service/MessageService.java
  dofarming/src/main/java/goorm/dofarming/domain/mongo/message/service/KafkaMessageService.java
  dofarming/src/main/java/goorm/dofarming/global/config/kafka/KafkaConsumerConfig.java
Labels: fix, chore

#78 Release to develop
  chat/src/main/java/goorm/chat/config/KafkaConsumerConfig.java
  chat/src/main/java/goorm/chat/config/KafkaProducerConfig.java
  chat/src/main/java/goorm/chat/service/MessageService.java
  dofarming/build.gradle
  dofarming/src/main/java/goorm/dofarming/domain/mongo/message/controller/MessageController.java
  dofarming/src/main/java/goorm/dofarming/domain/mongo/message/dto/MessageDto.java
  dofarming/src/main/java/goorm/dofarming/domain/mongo/message/dto/response/MessageResponse.java
  dofarming/src/main/java/goorm/dofarming/domain/mongo/message/entity/Message.java
  dofarming/src/main/java/goorm/dofarming/domain/mongo/message/repository/MessageRepositoryCustom.java
  dofarming/src/main/java/goorm/dofarming/domain/mongo/message/repository/MessageRepositoryImpl.java
  dofarming/src/main/java/goorm/dofarming/domain/mongo/message/service/KafkaMessageService.java
  dofarming/src/main/java/goorm/dofarming/domain/mongo/message/service/MessageService.java
  dofarming/src/main/java/goorm/dofarming/global/config/kafka/KafkaConsumerConfig.java
  dofarming/src/main/resources/application.properties
Labels: feat, chore

#77 feature/RAND-12
  dofarming/src/main/java/goorm/dofarming/domain/jpa/auth/dto/request/OauthRequest.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/auth/dto/response/MyInfoResponse.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/dto/request/ChatroomCreateRequest.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/dto/response/ChatroomResponse.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/service/ChatroomService.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/tag/dto/response/TagResponse.java
  dofarming/src/main/java/goorm/dofarming/domain/mongo/message/dto/MessageDto.java
  dofarming/src/main/java/goorm/dofarming/domain/mongo/message/dto/response/MessageResponse.java
  dofarming/src/main/java/goorm/dofarming/infra/tourapi/dto/Item.java
Labels: feat

#81 feature/RAND-97
  chat/src/main/java/goorm/chat/controller/MessageController.java
  chat/src/main/java/goorm/chat/domain/MessageType.java
  chat/src/main/resources/application.properties
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/dto/response/ChatroomResponse.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/entity/Region.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/join/dto/request/AlarmDto.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/join/repository/JoinRepository.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/join/service/KafkaJoinService.java
  dofarming/src/main/java/goorm/dofarming/domain/mongo/message/dto/response/MessageResponse.java
  dofarming/src/main/java/goorm/dofarming/domain/mongo/message/service/KafkaMessageService.java
  dofarming/src/main/java/goorm/dofarming/global/config/kafka/KafkaConstants.java
  dofarming/src/main/java/goorm/dofarming/global/util/RandomGenerator.java
  notification/.gitignore
  notification/build.gradle
  notification/gradle/wrapper/gradle-wrapper.jar
  notification/gradle/wrapper/gradle-wrapper.properties
  notification/gradlew
  notification/gradlew.bat
  notification/settings.gradle
  notification/src/main/java/goorm/notification/NotificationApplication.java
  notification/src/main/java/goorm/notification/config/kafka/KafkaConstants.java
  notification/src/main/java/goorm/notification/config/kafka/KafkaConsumerConfig.java
  notification/src/main/java/goorm/notification/controller/NotificationController.java
  notification/src/main/java/goorm/notification/dto/AlarmDto.java
  notification/src/main/java/goorm/notification/repository/EmitterRepository.java
  notification/src/main/java/goorm/notification/service/NotificationService.java
  notification/src/main/resources/application.properties
  notification/src/test/java/goorm/notification/NotificationApplicationTests.java
Labels: fix, feat

#83 feature/RAND-97
  dofarming/src/main/java/goorm/dofarming/domain/jpa/auth/service/AuthService.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/user/repository/UserRepository.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/user/service/UserService.java
  dofarming/src/main/java/goorm/dofarming/global/util/RandomGenerator.java
Labels: fix, feat

#84 Release to main
  dofarming/src/main/java/goorm/dofarming/domain/jpa/auth/service/AuthService.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/user/repository/UserRepository.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/user/service/UserService.java
  dofarming/src/main/java/goorm/dofarming/global/util/RandomGenerator.java
Labels: chore

#85 Release to main
  dofarming/src/main/java/goorm/dofarming/global/config/kafka/KafkaProducerConfig.java
  dofarming/src/main/resources/application.properties
Labels: fix, chore

#92 develop to release
  chat/src/main/java/goorm/chat/config/KafkaConstants.java
  chat/src/main/java/goorm/chat/dto/MessageResponse.java
  chat/src/main/java/goorm/chat/service/MessageService.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/auth/service/AuthService.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/dto/response/MyChatroomResponse.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/join/controller/JoinController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/join/dto/request/WatermarkRequest.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/join/entity/Join.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/join/service/JoinService.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/message/entity/Message.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/message/service/KafkaMessageService.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/user/dto/request/UserModifyRequest.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/user/entity/User.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/user/service/UserService.java
  dofarming/src/main/java/goorm/dofarming/global/config/kafka/KafkaConstants.java
  dofarming/src/main/resources/application.properties
Labels: fix, chore

#93 Develop to main
  chat/src/main/java/goorm/chat/config/KafkaConstants.java
  chat/src/main/java/goorm/chat/dto/MessageResponse.java
  chat/src/main/java/goorm/chat/service/MessageService.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/auth/service/AuthService.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/dto/response/MyChatroomResponse.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/join/controller/JoinController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/join/dto/request/WatermarkRequest.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/join/entity/Join.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/join/service/JoinService.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/location/entity/Location.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/log/controller/LogController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/log/entity/Log.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/log/repository/LogRepository.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/log/service/LogService.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/message/entity/Message.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/message/service/KafkaMessageService.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/recommend/controller/RecommendController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/recommend/service/RecommendService.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/user/dto/request/UserModifyRequest.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/user/entity/User.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/user/service/UserService.java
  dofarming/src/main/java/goorm/dofarming/global/config/kafka/KafkaConstants.java
  dofarming/src/main/resources/application.properties
Labels: fix, feat, chore

#94 fix: 이미지 경로 수정
  dofarming/src/main/java/goorm/dofarming/domain/jpa/user/service/UserService.java
  dofarming/src/main/java/goorm/dofarming/global/util/ImageUtil.java
  dofarming/src/main/resources/application.properties
Labels: fix, chore

#95 fix: 이미지 경로 수정
  dofarming/src/main/java/goorm/dofarming/domain/jpa/user/service/UserService.java
Labels: fix, chore

#97 feature/RAND-119
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/controller/ChatroomController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/repository/ChatroomRepositoryImpl.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/service/ChatroomService.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/join/entity/Join.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/join/service/JoinService.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/message/controller/MessageController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/message/repository/MessageRepositoryCustom.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/message/repository/MessageRepositoryImpl.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/message/service/MessageService.java
Labels: fix, feat, chore

#102 Feature/RAND-12 : 좋아요, 로그, 추천 기능 api 명세서 작성
  dofarming/src/main/java/goorm/dofarming/domain/jpa/like/controller/LikeController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/log/controller/LogController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/recommend/controller/RecommendController.java
Labels: feat
