Repository goorm-dofarming/Backend, pull requests merged in 2024-08, with the labels that each got.

#108 feature/RAND-123
  dofarming/src/main/java/goorm/dofarming/domain/jpa/like/controller/LikeController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/like/entity/Like.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/like/entity/LikeDTO.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/like/repository/LikeRepository.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/like/service/LikeService.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/location/dto/response/LocationResponse.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/location/entity/Location.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/location/repository/LocationRepository.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/log/controller/LogController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/log/dto/response/LogResponse.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/log/repository/LogRepository.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/log/service/LogService.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/recommend/entity/Recommend.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/recommend/entity/RecommendDTO.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/recommend/service/RecommendService.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/user/entity/User.java
  dofarming/src/main/java/goorm/dofarming/infra/tourapi/config/WebClientConfig.java
  dofarming/src/main/java/goorm/dofarming/infra/tourapi/domain/Activity.java
  dofarming/src/main/java/goorm/dofarming/infra/tourapi/domain/Cafe.java
  dofarming/src/main/java/goorm/dofarming/infra/tourapi/domain/Mountain.java
  dofarming/src/main/java/goorm/dofarming/infra/tourapi/domain/Ocean.java
  dofarming/src/main/java/goorm/dofarming/infra/tourapi/domain/Restaurant.java
  dofarming/src/main/java/goorm/dofarming/infra/tourapi/domain/Tour.java
  dofarming/src/main/resources/application.properties
Labels: fix, refactor, feat

#116 feature/RAND-127 feat: 좋아요 리스트 정렬 기능 구현
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/entity/Region.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/like/controller/LikeController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/like/entity/Like.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/like/entity/SortType.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/like/repository/LikeRepository.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/like/repository/LikeRepositoryCustom.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/like/repository/LikeRepositoryImpl.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/like/service/LikeService.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/location/dto/response/LocationResponse.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/location/entity/Location.java
  dofarming/src/main/java/goorm/dofarming/global/common/entity/BaseEntity.java
Labels: feat

#123 feature/RAND-127
  dofarming/src/main/java/goorm/dofarming/domain/jpa/like/repository/LikeRepositoryImpl.java
Labels: fix

#124 Release to develop
  dofarming/src/main/java/goorm/dofarming/domain/jpa/like/repository/LikeRepositoryImpl.java
Labels: chore

#126 feature/RAND-129
  dofarming/src/main/java/goorm/dofarming/domain/jpa/image/dto/response/ImageResponse.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/image/entity/Image.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/like/repository/LikeRepositoryImpl.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/location/entity/Location.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review/controller/ReviewController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review/dto/ReviewDTO.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review/dto/ReviewLocationResponse.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review/dto/ReviewResponse.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review/dto/request/ReviewCreateRequest.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review/dto/request/ReviewModifyRequest.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review/entity/Review.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review/service/ReviewService.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/user/dto/response/UserResponse.java
Labels: refactor

#128 Release to develop
  dofarming/src/main/java/goorm/dofarming/domain/jpa/image/dto/response/ImageResponse.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/image/entity/Image.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/like/repository/LikeRepositoryImpl.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/location/entity/Location.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review/controller/ReviewController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review/dto/ReviewDTO.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review/dto/ReviewLocationResponse.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review/dto/ReviewResponse.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review/dto/request/ReviewCreateRequest.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review/dto/request/ReviewModifyRequest.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review/entity/Review.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review/service/ReviewService.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/user/dto/response/UserResponse.java
Labels: chore

#129 feature/RAND-129
  dofarming/src/main/java/goorm/dofarming/domain/jpa/like/repository/LikeRepository.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/location/controller/LocationController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/location/dto/response/LocationResponse.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/location/repository/LocationRepository.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/location/service/LocationService.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review/controller/ReviewController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review/dto/ReviewDTO.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review/repository/ReviewRepository.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review/repository/ReviewRepositoryCustom.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review/repository/ReviewRepositoryImpl.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review/service/ReviewService.java
Labels: fix, feat

#130 Release to devleop
  dofarming/src/main/java/goorm/dofarming/domain/jpa/like/repository/LikeRepository.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/location/controller/LocationController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/location/dto/response/LocationResponse.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/location/repository/LocationRepository.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/location/service/LocationService.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review/controller/ReviewController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review/dto/ReviewDTO.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review/repository/ReviewRepository.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review/repository/ReviewRepositoryCustom.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review/repository/ReviewRepositoryImpl.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review/service/ReviewService.java
Labels: chore

#133 feature/RAND-129
  dofarming/src/main/java/goorm/dofarming/domain/jpa/like/dto/response/LikeResponse.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/location/dto/response/LocationResponse.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/location/entity/Location.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/location/service/LocationService.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/log/controller/LogController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/log/service/LogService.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/recommend/service/RecommendService.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review/controller/ReviewController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review/dto/ReviewResponse.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review/entity/Review.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review/repository/ReviewRepository.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review/repository/ReviewRepositoryCustom.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review/repository/ReviewRepositoryImpl.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review/service/ReviewService.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review_like/repository/ReviewLikeRepository.java
Labels: refactor, feat

#134 Release to develop
  dofarming/src/main/java/goorm/dofarming/domain/jpa/like/dto/response/LikeResponse.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/location/dto/response/LocationResponse.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/location/entity/Location.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/location/service/LocationService.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/log/controller/LogController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/log/service/LogService.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/recommend/service/RecommendService.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review/controller/ReviewController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review/dto/ReviewResponse.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review/entity/Review.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review/repository/ReviewRepository.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review/repository/ReviewRepositoryCustom.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review/repository/ReviewRepositoryImpl.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review/service/ReviewService.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review_like/repository/ReviewLikeRepository.java
Labels: chore

#136 Release to develop
  dofarming/src/main/java/goorm/dofarming/domain/jpa/image/repository/ImageRepository.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/image/repository/ImageRepositoryCustom.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/image/repository/ImageRepositoryImpl.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/like/dto/response/LikeResponse.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/like/service/LikeService.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/location/dto/response/LocationResponse.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/location/service/LocationService.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/log/controller/LogController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/log/service/LogService.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/recommend/service/RecommendService.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review/controller/ReviewController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review/repository/ReviewRepository.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review/repository/ReviewRepositoryCustom.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review/repository/ReviewRepositoryImpl.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review/service/ReviewService.java
Labels: fix, feat, chore

#137 feature/RAND-12 : 8월 6일자 swagger 수정 및 추가
  dofarming/src/main/java/goorm/dofarming/domain/jpa/auth/controller/AuthController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/controller/ChatroomController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/dto/response/MyChatroomResponse.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/email/controller/EmailController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/email/dto/request/EmailCheckRequest.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/email/dto/request/EmailRequest.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/image/controller/ImageController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/image/dto/response/ImageResponse.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/join/controller/JoinController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/join/dto/request/AlarmDto.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/join/dto/request/WatermarkRequest.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/like/controller/LikeController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/like/dto/response/LikeResponse.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/like/entity/Like.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/location/controller/LocationController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/location/dto/response/LocationResponse.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/log/controller/LogController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/log/dto/response/LogResponse.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/log/entity/Log.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/message/controller/MessageController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/message/dto/response/MessageResponse.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/message/dto/response/SimpleMessageResponse.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/message/entity/Message.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/recommend/controller/RecommendController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/recommend/entity/RecommendDTO.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review/controller/ReviewController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review/dto/ReviewResponse.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review/dto/request/ReviewCreateRequest.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review/dto/request/ReviewModifyRequest.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review_like/controller/ReviewLikeController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/user/controller/UserController.java
Labels: fix, refactor, feat

#138 Release to develop
  dofarming/src/main/java/goorm/dofarming/domain/jpa/auth/controller/AuthController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/controller/ChatroomController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/chatroom/dto/response/MyChatroomResponse.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/email/controller/EmailController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/email/dto/request/EmailCheckRequest.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/email/dto/request/EmailRequest.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/image/controller/ImageController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/image/dto/response/ImageResponse.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/image/repository/ImageRepositoryImpl.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/join/controller/JoinController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/join/dto/request/AlarmDto.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/join/dto/request/WatermarkRequest.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/like/controller/LikeController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/like/dto/response/LikeResponse.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/like/entity/Like.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/like/service/LikeService.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/location/controller/LocationController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/location/dto/response/LocationResponse.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/location/service/LocationService.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/log/controller/LogController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/log/dto/response/LogResponse.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/log/entity/Log.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/log/service/LogService.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/message/controller/MessageController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/message/dto/response/MessageResponse.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/message/dto/response/SimpleMessageResponse.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/message/entity/Message.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/recommend/controller/RecommendController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/recommend/entity/RecommendDTO.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/recommend/service/RecommendService.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review/controller/ReviewController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review/dto/ReviewResponse.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review/dto/request/ReviewCreateRequest.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review/dto/request/ReviewModifyRequest.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review/repository/ReviewRepositoryImpl.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review_like/controller/ReviewLikeController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/user/controller/UserController.java
Labels: fix, chore

#148 feature/RAND-12 : test api 삭제
  dofarming/src/main/java/goorm/dofarming/infra/tourapi/controller/ApiController.java
  dofarming/src/main/java/goorm/dofarming/infra/tourapi/controller/TestController.java
Labels: remove

#151 feature/RAND-134
  chat/src/main/java/goorm/chat/config/WebSocketConfig.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/like/repository/LikeRepositoryImpl.java
Labels: fix, feat

#152 release to develop
  chat/src/main/java/goorm/chat/config/WebSocketConfig.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/like/repository/LikeRepositoryImpl.java
Labels: chore

#153 feat: 좋아요 리스트 평점 정렬 기능 구현
  dofarming/src/main/java/goorm/dofarming/domain/jpa/like/controller/LikeController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/like/repository/LikeRepositoryCustom.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/like/repository/LikeRepositoryImpl.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/like/service/LikeService.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/location/entity/Location.java
Labels: fix, feat

#154 release to develop
  dofarming/src/main/java/goorm/dofarming/domain/jpa/like/controller/LikeController.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/like/repository/LikeRepositoryCustom.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/like/repository/LikeRepositoryImpl.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/like/service/LikeService.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/location/entity/Location.java
Labels: chore

#155 refactor: rest api refactor
  dofarming/src/main/java/goorm/dofarming/domain/jpa/image/entity/Image.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/log/entity/Log.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/review/entity/Review.java
Labels: refactor

#160 dofarming v1
  dofarming/src/main/java/goorm/dofarming/domain/jpa/message/entity/Message.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/message/service/KafkaMessageService.java
  dofarming/src/main/java/goorm/dofarming/domain/jpa/message/service/MessageService.java
Labels: fix, refactor, chore
